// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminGetCostByDay = `-- name: AdminGetCostByDay :many
SELECT
    date_trunc('day', created_at)::date AS day,
    COUNT(*)::int AS newsletter_count,
    COALESCE(SUM(cost_usd), 0)::numeric(10,4) AS cost_usd
FROM newsletters
WHERE created_at >= NOW() - INTERVAL '30 days'
GROUP BY date_trunc('day', created_at)
ORDER BY day DESC
`

type AdminGetCostByDayRow struct {
	Day             pgtype.Date    `json:"day"`
	NewsletterCount int32          `json:"newsletter_count"`
	CostUsd         pgtype.Numeric `json:"cost_usd"`
}

func (q *Queries) AdminGetCostByDay(ctx context.Context) ([]AdminGetCostByDayRow, error) {
	rows, err := q.db.Query(ctx, adminGetCostByDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminGetCostByDayRow{}
	for rows.Next() {
		var i AdminGetCostByDayRow
		if err := rows.Scan(&i.Day, &i.NewsletterCount, &i.CostUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminGetMessageStats = `-- name: AdminGetMessageStats :one
SELECT
    COUNT(*)::int AS total_messages,
    COUNT(*) FILTER (WHERE sent_at >= NOW() - INTERVAL '7 days')::int AS messages_7d,
    COUNT(*) FILTER (WHERE sent_at >= NOW() - INTERVAL '30 days')::int AS messages_30d
FROM messages
`

type AdminGetMessageStatsRow struct {
	TotalMessages int32 `json:"total_messages"`
	Messages7d    int32 `json:"messages_7d"`
	Messages30d   int32 `json:"messages_30d"`
}

func (q *Queries) AdminGetMessageStats(ctx context.Context) (AdminGetMessageStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetMessageStats)
	var i AdminGetMessageStatsRow
	err := row.Scan(&i.TotalMessages, &i.Messages7d, &i.Messages30d)
	return i, err
}

const adminGetNewsletterStats = `-- name: AdminGetNewsletterStats :one
SELECT
    COUNT(*)::int AS total_newsletters,
    COUNT(*) FILTER (WHERE status = 'draft')::int AS draft_count,
    COUNT(*) FILTER (WHERE status = 'published')::int AS published_count,
    COUNT(*) FILTER (WHERE status = 'error')::int AS error_count,
    COUNT(*) FILTER (WHERE is_on_demand = true)::int AS on_demand_count,
    COUNT(*) FILTER (WHERE is_on_demand = false)::int AS scheduled_count,
    COALESCE(SUM(cost_usd), 0)::numeric(10,4) AS total_cost_usd,
    COALESCE(SUM(pass1_tokens_in + pass1_tokens_out + pass2_tokens_in + pass2_tokens_out), 0)::bigint AS total_tokens,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '7 days')::int AS newsletters_7d,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '30 days')::int AS newsletters_30d
FROM newsletters
`

type AdminGetNewsletterStatsRow struct {
	TotalNewsletters int32          `json:"total_newsletters"`
	DraftCount       int32          `json:"draft_count"`
	PublishedCount   int32          `json:"published_count"`
	ErrorCount       int32          `json:"error_count"`
	OnDemandCount    int32          `json:"on_demand_count"`
	ScheduledCount   int32          `json:"scheduled_count"`
	TotalCostUsd     pgtype.Numeric `json:"total_cost_usd"`
	TotalTokens      int64          `json:"total_tokens"`
	Newsletters7d    int32          `json:"newsletters_7d"`
	Newsletters30d   int32          `json:"newsletters_30d"`
}

func (q *Queries) AdminGetNewsletterStats(ctx context.Context) (AdminGetNewsletterStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetNewsletterStats)
	var i AdminGetNewsletterStatsRow
	err := row.Scan(
		&i.TotalNewsletters,
		&i.DraftCount,
		&i.PublishedCount,
		&i.ErrorCount,
		&i.OnDemandCount,
		&i.ScheduledCount,
		&i.TotalCostUsd,
		&i.TotalTokens,
		&i.Newsletters7d,
		&i.Newsletters30d,
	)
	return i, err
}

const adminGetServerStats = `-- name: AdminGetServerStats :one
SELECT
    COUNT(*)::int AS total_servers,
    COUNT(*) FILTER (WHERE status = 'active')::int AS active_servers,
    COUNT(*) FILTER (WHERE status = 'removed')::int AS removed_servers
FROM servers
`

type AdminGetServerStatsRow struct {
	TotalServers   int32 `json:"total_servers"`
	ActiveServers  int32 `json:"active_servers"`
	RemovedServers int32 `json:"removed_servers"`
}

func (q *Queries) AdminGetServerStats(ctx context.Context) (AdminGetServerStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetServerStats)
	var i AdminGetServerStatsRow
	err := row.Scan(&i.TotalServers, &i.ActiveServers, &i.RemovedServers)
	return i, err
}

const adminGetUserStats = `-- name: AdminGetUserStats :one
SELECT
    COUNT(*)::int AS total_users,
    COUNT(*) FILTER (WHERE subscription_status = 'active')::int AS active_users,
    COUNT(*) FILTER (WHERE subscription_status = 'trialing')::int AS trialing_users,
    COUNT(*) FILTER (WHERE subscription_status = 'inactive')::int AS inactive_users,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '7 days')::int AS new_users_7d,
    COUNT(*) FILTER (WHERE created_at >= NOW() - INTERVAL '30 days')::int AS new_users_30d
FROM users
`

type AdminGetUserStatsRow struct {
	TotalUsers    int32 `json:"total_users"`
	ActiveUsers   int32 `json:"active_users"`
	TrialingUsers int32 `json:"trialing_users"`
	InactiveUsers int32 `json:"inactive_users"`
	NewUsers7d    int32 `json:"new_users_7d"`
	NewUsers30d   int32 `json:"new_users_30d"`
}

func (q *Queries) AdminGetUserStats(ctx context.Context) (AdminGetUserStatsRow, error) {
	row := q.db.QueryRow(ctx, adminGetUserStats)
	var i AdminGetUserStatsRow
	err := row.Scan(
		&i.TotalUsers,
		&i.ActiveUsers,
		&i.TrialingUsers,
		&i.InactiveUsers,
		&i.NewUsers7d,
		&i.NewUsers30d,
	)
	return i, err
}

const adminListRecentNewsletters = `-- name: AdminListRecentNewsletters :many
SELECT
    n.id, n.status, n.cost_usd, n.is_on_demand, n.created_at,
    n.pass1_tokens_in, n.pass1_tokens_out, n.pass2_tokens_in, n.pass2_tokens_out,
    s.name AS server_name,
    u.discord_username
FROM newsletters n
JOIN servers s ON s.id = n.server_id
JOIN users u ON u.id = s.user_id
ORDER BY n.created_at DESC
LIMIT 50
`

type AdminListRecentNewslettersRow struct {
	ID              pgtype.UUID        `json:"id"`
	Status          string             `json:"status"`
	CostUsd         pgtype.Numeric     `json:"cost_usd"`
	IsOnDemand      bool               `json:"is_on_demand"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Pass1TokensIn   int32              `json:"pass1_tokens_in"`
	Pass1TokensOut  int32              `json:"pass1_tokens_out"`
	Pass2TokensIn   int32              `json:"pass2_tokens_in"`
	Pass2TokensOut  int32              `json:"pass2_tokens_out"`
	ServerName      string             `json:"server_name"`
	DiscordUsername string             `json:"discord_username"`
}

func (q *Queries) AdminListRecentNewsletters(ctx context.Context) ([]AdminListRecentNewslettersRow, error) {
	rows, err := q.db.Query(ctx, adminListRecentNewsletters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRecentNewslettersRow{}
	for rows.Next() {
		var i AdminListRecentNewslettersRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.CostUsd,
			&i.IsOnDemand,
			&i.CreatedAt,
			&i.Pass1TokensIn,
			&i.Pass1TokensOut,
			&i.Pass2TokensIn,
			&i.Pass2TokensOut,
			&i.ServerName,
			&i.DiscordUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListRecentUsers = `-- name: AdminListRecentUsers :many
SELECT
    u.id, u.discord_username, u.email, u.subscription_status,
    u.trial_ends_at, u.created_at,
    COUNT(DISTINCT s.id)::int AS server_count,
    COUNT(DISTINCT n.id)::int AS newsletter_count
FROM users u
LEFT JOIN servers s ON s.user_id = u.id AND s.status = 'active'
LEFT JOIN newsletters n ON n.server_id = s.id
GROUP BY u.id
ORDER BY u.created_at DESC
LIMIT 50
`

type AdminListRecentUsersRow struct {
	ID                 pgtype.UUID        `json:"id"`
	DiscordUsername    string             `json:"discord_username"`
	Email              string             `json:"email"`
	SubscriptionStatus string             `json:"subscription_status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	ServerCount        int32              `json:"server_count"`
	NewsletterCount    int32              `json:"newsletter_count"`
}

func (q *Queries) AdminListRecentUsers(ctx context.Context) ([]AdminListRecentUsersRow, error) {
	rows, err := q.db.Query(ctx, adminListRecentUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListRecentUsersRow{}
	for rows.Next() {
		var i AdminListRecentUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DiscordUsername,
			&i.Email,
			&i.SubscriptionStatus,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.ServerCount,
			&i.NewsletterCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
