// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMonitoredChannel = `-- name: AddMonitoredChannel :one
INSERT INTO monitored_channels (server_id, discord_channel_id, name)
VALUES ($1, $2, $3)
ON CONFLICT (server_id, discord_channel_id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, server_id, discord_channel_id, name, created_at
`

type AddMonitoredChannelParams struct {
	ServerID         pgtype.UUID `json:"server_id"`
	DiscordChannelID string      `json:"discord_channel_id"`
	Name             string      `json:"name"`
}

func (q *Queries) AddMonitoredChannel(ctx context.Context, arg AddMonitoredChannelParams) (MonitoredChannel, error) {
	row := q.db.QueryRow(ctx, addMonitoredChannel, arg.ServerID, arg.DiscordChannelID, arg.Name)
	var i MonitoredChannel
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DiscordChannelID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMonitoredChannel = `-- name: DeleteMonitoredChannel :exec
DELETE FROM monitored_channels WHERE server_id = $1 AND discord_channel_id = $2
`

type DeleteMonitoredChannelParams struct {
	ServerID         pgtype.UUID `json:"server_id"`
	DiscordChannelID string      `json:"discord_channel_id"`
}

func (q *Queries) DeleteMonitoredChannel(ctx context.Context, arg DeleteMonitoredChannelParams) error {
	_, err := q.db.Exec(ctx, deleteMonitoredChannel, arg.ServerID, arg.DiscordChannelID)
	return err
}

const getMonitoredChannel = `-- name: GetMonitoredChannel :one
SELECT id, server_id, discord_channel_id, name, created_at FROM monitored_channels WHERE server_id = $1 AND discord_channel_id = $2
`

type GetMonitoredChannelParams struct {
	ServerID         pgtype.UUID `json:"server_id"`
	DiscordChannelID string      `json:"discord_channel_id"`
}

func (q *Queries) GetMonitoredChannel(ctx context.Context, arg GetMonitoredChannelParams) (MonitoredChannel, error) {
	row := q.db.QueryRow(ctx, getMonitoredChannel, arg.ServerID, arg.DiscordChannelID)
	var i MonitoredChannel
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.DiscordChannelID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getServerAndChannelByDiscordIDs = `-- name: GetServerAndChannelByDiscordIDs :one
SELECT mc.id AS channel_id, s.id AS server_id FROM monitored_channels mc
JOIN servers s ON mc.server_id = s.id
WHERE s.discord_guild_id = $1 AND mc.discord_channel_id = $2 AND s.status = 'active'
`

type GetServerAndChannelByDiscordIDsParams struct {
	DiscordGuildID   string `json:"discord_guild_id"`
	DiscordChannelID string `json:"discord_channel_id"`
}

type GetServerAndChannelByDiscordIDsRow struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	ServerID  pgtype.UUID `json:"server_id"`
}

func (q *Queries) GetServerAndChannelByDiscordIDs(ctx context.Context, arg GetServerAndChannelByDiscordIDsParams) (GetServerAndChannelByDiscordIDsRow, error) {
	row := q.db.QueryRow(ctx, getServerAndChannelByDiscordIDs, arg.DiscordGuildID, arg.DiscordChannelID)
	var i GetServerAndChannelByDiscordIDsRow
	err := row.Scan(&i.ChannelID, &i.ServerID)
	return i, err
}

const isChannelMonitored = `-- name: IsChannelMonitored :one
SELECT EXISTS(
    SELECT 1 FROM monitored_channels mc
    JOIN servers s ON mc.server_id = s.id
    WHERE s.discord_guild_id = $1 AND mc.discord_channel_id = $2
) AS is_monitored
`

type IsChannelMonitoredParams struct {
	DiscordGuildID   string `json:"discord_guild_id"`
	DiscordChannelID string `json:"discord_channel_id"`
}

func (q *Queries) IsChannelMonitored(ctx context.Context, arg IsChannelMonitoredParams) (bool, error) {
	row := q.db.QueryRow(ctx, isChannelMonitored, arg.DiscordGuildID, arg.DiscordChannelID)
	var is_monitored bool
	err := row.Scan(&is_monitored)
	return is_monitored, err
}

const listMonitoredChannels = `-- name: ListMonitoredChannels :many
SELECT id, server_id, discord_channel_id, name, created_at FROM monitored_channels WHERE server_id = $1 ORDER BY name
`

func (q *Queries) ListMonitoredChannels(ctx context.Context, serverID pgtype.UUID) ([]MonitoredChannel, error) {
	rows, err := q.db.Query(ctx, listMonitoredChannels, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonitoredChannel{}
	for rows.Next() {
		var i MonitoredChannel
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.DiscordChannelID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
