// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guild_free_generations.sql

package db

import (
	"context"
)

const guildFreeGenerationUsed = `-- name: GuildFreeGenerationUsed :one
SELECT EXISTS (
  SELECT 1 FROM guild_free_generations WHERE discord_guild_id = $1
)::bool
`

func (q *Queries) GuildFreeGenerationUsed(ctx context.Context, discordGuildID string) (bool, error) {
	row := q.db.QueryRow(ctx, guildFreeGenerationUsed, discordGuildID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const markGuildFreeGenerationUsed = `-- name: MarkGuildFreeGenerationUsed :exec
INSERT INTO guild_free_generations (discord_guild_id)
VALUES ($1)
ON CONFLICT (discord_guild_id) DO NOTHING
`

func (q *Queries) MarkGuildFreeGenerationUsed(ctx context.Context, discordGuildID string) error {
	_, err := q.db.Exec(ctx, markGuildFreeGenerationUsed, discordGuildID)
	return err
}
