// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getMessagesForGeneration = `-- name: GetMessagesForGeneration :many
SELECT m.id, m.discord_message_id, m.server_id, m.channel_id, m.discord_author_id, m.author_display_name, m.content, m.reply_to_discord_id, m.thread_discord_id, m.sent_at, m.reaction_count, m.reply_count, m.raw_payload, m.created_at FROM messages m
LEFT JOIN optouts o ON o.server_id = m.server_id AND o.discord_user_id = m.discord_author_id
WHERE m.server_id = $1
  AND m.sent_at >= $2
  AND m.sent_at <= $3
  AND o.id IS NULL
  AND m.content != '[deleted]'
ORDER BY m.sent_at ASC
`

type GetMessagesForGenerationParams struct {
	ServerID pgtype.UUID        `json:"server_id"`
	SentAt   pgtype.Timestamptz `json:"sent_at"`
	SentAt_2 pgtype.Timestamptz `json:"sent_at_2"`
}

func (q *Queries) GetMessagesForGeneration(ctx context.Context, arg GetMessagesForGenerationParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessagesForGeneration, arg.ServerID, arg.SentAt, arg.SentAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.DiscordMessageID,
			&i.ServerID,
			&i.ChannelID,
			&i.DiscordAuthorID,
			&i.AuthorDisplayName,
			&i.Content,
			&i.ReplyToDiscordID,
			&i.ThreadDiscordID,
			&i.SentAt,
			&i.ReactionCount,
			&i.ReplyCount,
			&i.RawPayload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementReactionCount = `-- name: IncrementReactionCount :exec
UPDATE messages SET reaction_count = reaction_count + 1 WHERE discord_message_id = $1
`

func (q *Queries) IncrementReactionCount(ctx context.Context, discordMessageID string) error {
	_, err := q.db.Exec(ctx, incrementReactionCount, discordMessageID)
	return err
}

const insertMessage = `-- name: InsertMessage :exec
INSERT INTO messages (
    discord_message_id, server_id, channel_id, discord_author_id,
    author_display_name, content, reply_to_discord_id, thread_discord_id,
    sent_at, reaction_count, reply_count, raw_payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (discord_message_id) DO NOTHING
`

type InsertMessageParams struct {
	DiscordMessageID  string             `json:"discord_message_id"`
	ServerID          pgtype.UUID        `json:"server_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	DiscordAuthorID   string             `json:"discord_author_id"`
	AuthorDisplayName string             `json:"author_display_name"`
	Content           string             `json:"content"`
	ReplyToDiscordID  pgtype.Text        `json:"reply_to_discord_id"`
	ThreadDiscordID   pgtype.Text        `json:"thread_discord_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ReactionCount     int32              `json:"reaction_count"`
	ReplyCount        int32              `json:"reply_count"`
	RawPayload        []byte             `json:"raw_payload"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) error {
	_, err := q.db.Exec(ctx, insertMessage,
		arg.DiscordMessageID,
		arg.ServerID,
		arg.ChannelID,
		arg.DiscordAuthorID,
		arg.AuthorDisplayName,
		arg.Content,
		arg.ReplyToDiscordID,
		arg.ThreadDiscordID,
		arg.SentAt,
		arg.ReactionCount,
		arg.ReplyCount,
		arg.RawPayload,
	)
	return err
}

const softDeleteMessage = `-- name: SoftDeleteMessage :exec
UPDATE messages SET content = '[deleted]' WHERE discord_message_id = $1
`

func (q *Queries) SoftDeleteMessage(ctx context.Context, discordMessageID string) error {
	_, err := q.db.Exec(ctx, softDeleteMessage, discordMessageID)
	return err
}

const updateMessageContent = `-- name: UpdateMessageContent :exec
UPDATE messages SET content = $2 WHERE discord_message_id = $1
`

type UpdateMessageContentParams struct {
	DiscordMessageID string `json:"discord_message_id"`
	Content          string `json:"content"`
}

func (q *Queries) UpdateMessageContent(ctx context.Context, arg UpdateMessageContentParams) error {
	_, err := q.db.Exec(ctx, updateMessageContent, arg.DiscordMessageID, arg.Content)
	return err
}
