// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GuildFreeGeneration struct {
	DiscordGuildID string             `json:"discord_guild_id"`
	UsedAt         pgtype.Timestamptz `json:"used_at"`
}

type Message struct {
	ID                pgtype.UUID        `json:"id"`
	DiscordMessageID  string             `json:"discord_message_id"`
	ServerID          pgtype.UUID        `json:"server_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	DiscordAuthorID   string             `json:"discord_author_id"`
	AuthorDisplayName string             `json:"author_display_name"`
	Content           string             `json:"content"`
	ReplyToDiscordID  pgtype.Text        `json:"reply_to_discord_id"`
	ThreadDiscordID   pgtype.Text        `json:"thread_discord_id"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ReactionCount     int32              `json:"reaction_count"`
	ReplyCount        int32              `json:"reply_count"`
	RawPayload        []byte             `json:"raw_payload"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type MonitoredChannel struct {
	ID               pgtype.UUID        `json:"id"`
	ServerID         pgtype.UUID        `json:"server_id"`
	DiscordChannelID string             `json:"discord_channel_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Weight           pgtype.Numeric     `json:"weight"`
}

type Newsletter struct {
	ID             pgtype.UUID        `json:"id"`
	ServerID       pgtype.UUID        `json:"server_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Status         string             `json:"status"`
	DraftMarkdown  string             `json:"draft_markdown"`
	EditedMarkdown pgtype.Text        `json:"edited_markdown"`
	PublishedAt    pgtype.Timestamptz `json:"published_at"`
	PublishedUrl   pgtype.Text        `json:"published_url"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
	Pass1TokensIn  int32              `json:"pass1_tokens_in"`
	Pass1TokensOut int32              `json:"pass1_tokens_out"`
	Pass2TokensIn  int32              `json:"pass2_tokens_in"`
	Pass2TokensOut int32              `json:"pass2_tokens_out"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	IsOnDemand     bool               `json:"is_on_demand"`
	Sources        []byte             `json:"sources"`
}

type Optout struct {
	ID            pgtype.UUID        `json:"id"`
	ServerID      pgtype.UUID        `json:"server_id"`
	DiscordUserID string             `json:"discord_user_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PublisherConnection struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Platform        string             `json:"platform"`
	ApiKeyEncrypted string             `json:"api_key_encrypted"`
	PublicationID   pgtype.Text        `json:"publication_id"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Server struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	DiscordGuildID string             `json:"discord_guild_id"`
	Name           string             `json:"name"`
	IconUrl        pgtype.Text        `json:"icon_url"`
	CommunityType  pgtype.Text        `json:"community_type"`
	ScheduleCron   string             `json:"schedule_cron"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	VoiceSample    pgtype.Text        `json:"voice_sample"`
}

type User struct {
	ID                 pgtype.UUID        `json:"id"`
	DiscordID          string             `json:"discord_id"`
	DiscordUsername    string             `json:"discord_username"`
	Email              string             `json:"email"`
	AvatarUrl          pgtype.Text        `json:"avatar_url"`
	StripeCustomerID   pgtype.Text        `json:"stripe_customer_id"`
	SubscriptionStatus string             `json:"subscription_status"`
	TrialEndsAt        pgtype.Timestamptz `json:"trial_ends_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}
