// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: newsletters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOnDemandThisMonth = `-- name: CountOnDemandThisMonth :one
SELECT COUNT(*)::int FROM newsletters
WHERE server_id = $1
  AND is_on_demand = true
  AND created_at >= date_trunc('month', NOW())
`

func (q *Queries) CountOnDemandThisMonth(ctx context.Context, serverID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOnDemandThisMonth, serverID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createNewsletter = `-- name: CreateNewsletter :one
INSERT INTO newsletters (
    server_id, period_start, period_end, status, draft_markdown,
    cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out,
    error_message, is_on_demand, sources
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, server_id, period_start, period_end, status, draft_markdown, edited_markdown, published_at, published_url, cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out, error_message, created_at, updated_at, is_on_demand, sources
`

type CreateNewsletterParams struct {
	ServerID       pgtype.UUID        `json:"server_id"`
	PeriodStart    pgtype.Timestamptz `json:"period_start"`
	PeriodEnd      pgtype.Timestamptz `json:"period_end"`
	Status         string             `json:"status"`
	DraftMarkdown  string             `json:"draft_markdown"`
	CostUsd        pgtype.Numeric     `json:"cost_usd"`
	Pass1TokensIn  int32              `json:"pass1_tokens_in"`
	Pass1TokensOut int32              `json:"pass1_tokens_out"`
	Pass2TokensIn  int32              `json:"pass2_tokens_in"`
	Pass2TokensOut int32              `json:"pass2_tokens_out"`
	ErrorMessage   pgtype.Text        `json:"error_message"`
	IsOnDemand     bool               `json:"is_on_demand"`
	Sources        []byte             `json:"sources"`
}

func (q *Queries) CreateNewsletter(ctx context.Context, arg CreateNewsletterParams) (Newsletter, error) {
	row := q.db.QueryRow(ctx, createNewsletter,
		arg.ServerID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Status,
		arg.DraftMarkdown,
		arg.CostUsd,
		arg.Pass1TokensIn,
		arg.Pass1TokensOut,
		arg.Pass2TokensIn,
		arg.Pass2TokensOut,
		arg.ErrorMessage,
		arg.IsOnDemand,
		arg.Sources,
	)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DraftMarkdown,
		&i.EditedMarkdown,
		&i.PublishedAt,
		&i.PublishedUrl,
		&i.CostUsd,
		&i.Pass1TokensIn,
		&i.Pass1TokensOut,
		&i.Pass2TokensIn,
		&i.Pass2TokensOut,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOnDemand,
		&i.Sources,
	)
	return i, err
}

const getLatestNewsletterByServerID = `-- name: GetLatestNewsletterByServerID :one
SELECT id, server_id, period_start, period_end, status, draft_markdown, edited_markdown, published_at, published_url, cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out, error_message, created_at, updated_at, is_on_demand, sources FROM newsletters WHERE server_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestNewsletterByServerID(ctx context.Context, serverID pgtype.UUID) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getLatestNewsletterByServerID, serverID)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DraftMarkdown,
		&i.EditedMarkdown,
		&i.PublishedAt,
		&i.PublishedUrl,
		&i.CostUsd,
		&i.Pass1TokensIn,
		&i.Pass1TokensOut,
		&i.Pass2TokensIn,
		&i.Pass2TokensOut,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOnDemand,
		&i.Sources,
	)
	return i, err
}

const getNewsletterByID = `-- name: GetNewsletterByID :one
SELECT id, server_id, period_start, period_end, status, draft_markdown, edited_markdown, published_at, published_url, cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out, error_message, created_at, updated_at, is_on_demand, sources FROM newsletters WHERE id = $1
`

func (q *Queries) GetNewsletterByID(ctx context.Context, id pgtype.UUID) (Newsletter, error) {
	row := q.db.QueryRow(ctx, getNewsletterByID, id)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DraftMarkdown,
		&i.EditedMarkdown,
		&i.PublishedAt,
		&i.PublishedUrl,
		&i.CostUsd,
		&i.Pass1TokensIn,
		&i.Pass1TokensOut,
		&i.Pass2TokensIn,
		&i.Pass2TokensOut,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOnDemand,
		&i.Sources,
	)
	return i, err
}

const listNewslettersByServerID = `-- name: ListNewslettersByServerID :many
SELECT id, server_id, period_start, period_end, status, draft_markdown, edited_markdown, published_at, published_url, cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out, error_message, created_at, updated_at, is_on_demand, sources FROM newsletters WHERE server_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListNewslettersByServerID(ctx context.Context, serverID pgtype.UUID) ([]Newsletter, error) {
	rows, err := q.db.Query(ctx, listNewslettersByServerID, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Newsletter{}
	for rows.Next() {
		var i Newsletter
		if err := rows.Scan(
			&i.ID,
			&i.ServerID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.Status,
			&i.DraftMarkdown,
			&i.EditedMarkdown,
			&i.PublishedAt,
			&i.PublishedUrl,
			&i.CostUsd,
			&i.Pass1TokensIn,
			&i.Pass1TokensOut,
			&i.Pass2TokensIn,
			&i.Pass2TokensOut,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IsOnDemand,
			&i.Sources,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNewsletterMarkdown = `-- name: UpdateNewsletterMarkdown :one
UPDATE newsletters SET edited_markdown = $2, updated_at = NOW() WHERE id = $1 RETURNING id, server_id, period_start, period_end, status, draft_markdown, edited_markdown, published_at, published_url, cost_usd, pass1_tokens_in, pass1_tokens_out, pass2_tokens_in, pass2_tokens_out, error_message, created_at, updated_at, is_on_demand, sources
`

type UpdateNewsletterMarkdownParams struct {
	ID             pgtype.UUID `json:"id"`
	EditedMarkdown pgtype.Text `json:"edited_markdown"`
}

func (q *Queries) UpdateNewsletterMarkdown(ctx context.Context, arg UpdateNewsletterMarkdownParams) (Newsletter, error) {
	row := q.db.QueryRow(ctx, updateNewsletterMarkdown, arg.ID, arg.EditedMarkdown)
	var i Newsletter
	err := row.Scan(
		&i.ID,
		&i.ServerID,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Status,
		&i.DraftMarkdown,
		&i.EditedMarkdown,
		&i.PublishedAt,
		&i.PublishedUrl,
		&i.CostUsd,
		&i.Pass1TokensIn,
		&i.Pass1TokensOut,
		&i.Pass2TokensIn,
		&i.Pass2TokensOut,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsOnDemand,
		&i.Sources,
	)
	return i, err
}

const updateNewsletterPublished = `-- name: UpdateNewsletterPublished :exec
UPDATE newsletters SET
    status = 'published',
    published_url = $2,
    published_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

type UpdateNewsletterPublishedParams struct {
	ID           pgtype.UUID `json:"id"`
	PublishedUrl pgtype.Text `json:"published_url"`
}

func (q *Queries) UpdateNewsletterPublished(ctx context.Context, arg UpdateNewsletterPublishedParams) error {
	_, err := q.db.Exec(ctx, updateNewsletterPublished, arg.ID, arg.PublishedUrl)
	return err
}

const updateNewsletterStatus = `-- name: UpdateNewsletterStatus :exec
UPDATE newsletters SET status = $2, error_message = $3, updated_at = NOW() WHERE id = $1
`

type UpdateNewsletterStatusParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
}

func (q *Queries) UpdateNewsletterStatus(ctx context.Context, arg UpdateNewsletterStatusParams) error {
	_, err := q.db.Exec(ctx, updateNewsletterStatus, arg.ID, arg.Status, arg.ErrorMessage)
	return err
}
