// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: optouts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addOptout = `-- name: AddOptout :exec
INSERT INTO optouts (server_id, discord_user_id)
VALUES ($1, $2)
ON CONFLICT (server_id, discord_user_id) DO NOTHING
`

type AddOptoutParams struct {
	ServerID      pgtype.UUID `json:"server_id"`
	DiscordUserID string      `json:"discord_user_id"`
}

func (q *Queries) AddOptout(ctx context.Context, arg AddOptoutParams) error {
	_, err := q.db.Exec(ctx, addOptout, arg.ServerID, arg.DiscordUserID)
	return err
}

const isUserOptedOut = `-- name: IsUserOptedOut :one
SELECT EXISTS(
    SELECT 1 FROM optouts WHERE server_id = $1 AND discord_user_id = $2
) AS is_opted_out
`

type IsUserOptedOutParams struct {
	ServerID      pgtype.UUID `json:"server_id"`
	DiscordUserID string      `json:"discord_user_id"`
}

func (q *Queries) IsUserOptedOut(ctx context.Context, arg IsUserOptedOutParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserOptedOut, arg.ServerID, arg.DiscordUserID)
	var is_opted_out bool
	err := row.Scan(&is_opted_out)
	return is_opted_out, err
}

const listOptouts = `-- name: ListOptouts :many
SELECT discord_user_id FROM optouts WHERE server_id = $1
`

func (q *Queries) ListOptouts(ctx context.Context, serverID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listOptouts, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var discord_user_id string
		if err := rows.Scan(&discord_user_id); err != nil {
			return nil, err
		}
		items = append(items, discord_user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
