// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processed_stripe_events.sql

package db

import (
	"context"
)

const claimStripeEvent = `-- name: ClaimStripeEvent :one
INSERT INTO processed_stripe_events (event_id)
VALUES ($1)
ON CONFLICT (event_id) DO NOTHING
RETURNING event_id
`

// Atomically record that a Stripe event is being processed. Returns the
// event_id on a fresh insert; returns no row if the event was already
// processed (the caller treats "no row" as "skip, already handled").
func (q *Queries) ClaimStripeEvent(ctx context.Context, eventID string) (string, error) {
	row := q.db.QueryRow(ctx, claimStripeEvent, eventID)
	var event_id string
	err := row.Scan(&event_id)
	return event_id, err
}
