// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: publisher_connections.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deletePublisherConnection = `-- name: DeletePublisherConnection :exec
DELETE FROM publisher_connections WHERE user_id = $1 AND platform = $2
`

type DeletePublisherConnectionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
}

func (q *Queries) DeletePublisherConnection(ctx context.Context, arg DeletePublisherConnectionParams) error {
	_, err := q.db.Exec(ctx, deletePublisherConnection, arg.UserID, arg.Platform)
	return err
}

const getPublisherConnection = `-- name: GetPublisherConnection :one
SELECT id, user_id, platform, api_key_encrypted, publication_id, metadata, created_at FROM publisher_connections WHERE user_id = $1 AND platform = $2
`

type GetPublisherConnectionParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
}

func (q *Queries) GetPublisherConnection(ctx context.Context, arg GetPublisherConnectionParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, getPublisherConnection, arg.UserID, arg.Platform)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ApiKeyEncrypted,
		&i.PublicationID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listPublisherConnections = `-- name: ListPublisherConnections :many
SELECT id, user_id, platform, api_key_encrypted, publication_id, metadata, created_at FROM publisher_connections WHERE user_id = $1 ORDER BY platform
`

func (q *Queries) ListPublisherConnections(ctx context.Context, userID pgtype.UUID) ([]PublisherConnection, error) {
	rows, err := q.db.Query(ctx, listPublisherConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PublisherConnection{}
	for rows.Next() {
		var i PublisherConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.ApiKeyEncrypted,
			&i.PublicationID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPublisherConnection = `-- name: UpsertPublisherConnection :one
INSERT INTO publisher_connections (user_id, platform, api_key_encrypted, publication_id, metadata)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, platform) DO UPDATE SET
    api_key_encrypted = EXCLUDED.api_key_encrypted,
    publication_id = EXCLUDED.publication_id,
    metadata = EXCLUDED.metadata
RETURNING id, user_id, platform, api_key_encrypted, publication_id, metadata, created_at
`

type UpsertPublisherConnectionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	Platform        string      `json:"platform"`
	ApiKeyEncrypted string      `json:"api_key_encrypted"`
	PublicationID   pgtype.Text `json:"publication_id"`
	Metadata        []byte      `json:"metadata"`
}

func (q *Queries) UpsertPublisherConnection(ctx context.Context, arg UpsertPublisherConnectionParams) (PublisherConnection, error) {
	row := q.db.QueryRow(ctx, upsertPublisherConnection,
		arg.UserID,
		arg.Platform,
		arg.ApiKeyEncrypted,
		arg.PublicationID,
		arg.Metadata,
	)
	var i PublisherConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.ApiKeyEncrypted,
		&i.PublicationID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
