// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createServer = `-- name: CreateServer :one
INSERT INTO servers (user_id, discord_guild_id, name, icon_url, community_type)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, discord_guild_id) DO UPDATE SET
    name = EXCLUDED.name,
    icon_url = EXCLUDED.icon_url,
    status = 'active'
RETURNING id, user_id, discord_guild_id, name, icon_url, community_type, schedule_cron, status, created_at
`

type CreateServerParams struct {
	UserID         pgtype.UUID `json:"user_id"`
	DiscordGuildID string      `json:"discord_guild_id"`
	Name           string      `json:"name"`
	IconUrl        pgtype.Text `json:"icon_url"`
	CommunityType  pgtype.Text `json:"community_type"`
}

func (q *Queries) CreateServer(ctx context.Context, arg CreateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, createServer,
		arg.UserID,
		arg.DiscordGuildID,
		arg.Name,
		arg.IconUrl,
		arg.CommunityType,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordGuildID,
		&i.Name,
		&i.IconUrl,
		&i.CommunityType,
		&i.ScheduleCron,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByGuildID = `-- name: GetServerByGuildID :one
SELECT id, user_id, discord_guild_id, name, icon_url, community_type, schedule_cron, status, created_at FROM servers WHERE discord_guild_id = $1 AND status = 'active'
`

func (q *Queries) GetServerByGuildID(ctx context.Context, discordGuildID string) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByGuildID, discordGuildID)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordGuildID,
		&i.Name,
		&i.IconUrl,
		&i.CommunityType,
		&i.ScheduleCron,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getServerByID = `-- name: GetServerByID :one
SELECT id, user_id, discord_guild_id, name, icon_url, community_type, schedule_cron, status, created_at FROM servers WHERE id = $1
`

func (q *Queries) GetServerByID(ctx context.Context, id pgtype.UUID) (Server, error) {
	row := q.db.QueryRow(ctx, getServerByID, id)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordGuildID,
		&i.Name,
		&i.IconUrl,
		&i.CommunityType,
		&i.ScheduleCron,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveServersForSchedule = `-- name: ListActiveServersForSchedule :many
SELECT s.id, s.user_id, s.discord_guild_id, s.name, s.icon_url, s.community_type, s.schedule_cron, s.status, s.created_at FROM servers s
JOIN users u ON s.user_id = u.id
WHERE s.status = 'active'
  AND u.subscription_status IN ('trialing', 'active')
  AND (u.subscription_status != 'trialing' OR u.trial_ends_at > NOW())
`

func (q *Queries) ListActiveServersForSchedule(ctx context.Context) ([]Server, error) {
	rows, err := q.db.Query(ctx, listActiveServersForSchedule)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DiscordGuildID,
			&i.Name,
			&i.IconUrl,
			&i.CommunityType,
			&i.ScheduleCron,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServersByUserID = `-- name: ListServersByUserID :many
SELECT id, user_id, discord_guild_id, name, icon_url, community_type, schedule_cron, status, created_at FROM servers WHERE user_id = $1 AND status != 'removed' ORDER BY created_at DESC
`

func (q *Queries) ListServersByUserID(ctx context.Context, userID pgtype.UUID) ([]Server, error) {
	rows, err := q.db.Query(ctx, listServersByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Server{}
	for rows.Next() {
		var i Server
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DiscordGuildID,
			&i.Name,
			&i.IconUrl,
			&i.CommunityType,
			&i.ScheduleCron,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerRemoved = `-- name: SetServerRemoved :exec
UPDATE servers SET status = 'removed' WHERE discord_guild_id = $1
`

func (q *Queries) SetServerRemoved(ctx context.Context, discordGuildID string) error {
	_, err := q.db.Exec(ctx, setServerRemoved, discordGuildID)
	return err
}

const updateServer = `-- name: UpdateServer :one
UPDATE servers SET
    community_type = COALESCE($2, community_type),
    schedule_cron = COALESCE($3, schedule_cron),
    status = COALESCE($4, status),
    name = COALESCE($5, name)
WHERE id = $1
RETURNING id, user_id, discord_guild_id, name, icon_url, community_type, schedule_cron, status, created_at
`

type UpdateServerParams struct {
	ID            pgtype.UUID `json:"id"`
	CommunityType pgtype.Text `json:"community_type"`
	ScheduleCron  string      `json:"schedule_cron"`
	Status        string      `json:"status"`
	Name          string      `json:"name"`
}

func (q *Queries) UpdateServer(ctx context.Context, arg UpdateServerParams) (Server, error) {
	row := q.db.QueryRow(ctx, updateServer,
		arg.ID,
		arg.CommunityType,
		arg.ScheduleCron,
		arg.Status,
		arg.Name,
	)
	var i Server
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DiscordGuildID,
		&i.Name,
		&i.IconUrl,
		&i.CommunityType,
		&i.ScheduleCron,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
