// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: usage_counters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const incrementUsageCounter = `-- name: IncrementUsageCounter :one
INSERT INTO usage_counters (user_id, kind, day, count)
VALUES ($1, $2, CURRENT_DATE, 1)
ON CONFLICT (user_id, kind, day)
DO UPDATE SET count = usage_counters.count + 1
RETURNING count
`

type IncrementUsageCounterParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Kind   string      `json:"kind"`
}

// Atomically bump today's counter for (user, kind) and return the new
// count. The caller compares the returned count against a per-kind
// limit; doing the increment-then-read in one statement closes the
// check-then-act race.
func (q *Queries) IncrementUsageCounter(ctx context.Context, arg IncrementUsageCounterParams) (int32, error) {
	row := q.db.QueryRow(ctx, incrementUsageCounter, arg.UserID, arg.Kind)
	var count int32
	err := row.Scan(&count)
	return count, err
}
