// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getTrialExpiringUsers = `-- name: GetTrialExpiringUsers :many
SELECT id, discord_id, discord_username, email, avatar_url, stripe_customer_id, subscription_status, trial_ends_at, created_at, updated_at FROM users
WHERE subscription_status = 'trialing'
  AND trial_ends_at BETWEEN NOW() AND NOW() + INTERVAL '2 days'
`

func (q *Queries) GetTrialExpiringUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getTrialExpiringUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.DiscordID,
			&i.DiscordUsername,
			&i.Email,
			&i.AvatarUrl,
			&i.StripeCustomerID,
			&i.SubscriptionStatus,
			&i.TrialEndsAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByDiscordID = `-- name: GetUserByDiscordID :one
SELECT id, discord_id, discord_username, email, avatar_url, stripe_customer_id, subscription_status, trial_ends_at, created_at, updated_at FROM users WHERE discord_id = $1
`

func (q *Queries) GetUserByDiscordID(ctx context.Context, discordID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByDiscordID, discordID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, discord_id, discord_username, email, avatar_url, stripe_customer_id, subscription_status, trial_ends_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByStripeCustomerID = `-- name: GetUserByStripeCustomerID :one
SELECT id, discord_id, discord_username, email, avatar_url, stripe_customer_id, subscription_status, trial_ends_at, created_at, updated_at FROM users WHERE stripe_customer_id = $1
`

func (q *Queries) GetUserByStripeCustomerID(ctx context.Context, stripeCustomerID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomerID, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateStripeCustomerID = `-- name: UpdateStripeCustomerID :exec
UPDATE users SET stripe_customer_id = $2, updated_at = NOW() WHERE id = $1
`

type UpdateStripeCustomerIDParams struct {
	ID               pgtype.UUID `json:"id"`
	StripeCustomerID pgtype.Text `json:"stripe_customer_id"`
}

func (q *Queries) UpdateStripeCustomerID(ctx context.Context, arg UpdateStripeCustomerIDParams) error {
	_, err := q.db.Exec(ctx, updateStripeCustomerID, arg.ID, arg.StripeCustomerID)
	return err
}

const updateSubscriptionStatus = `-- name: UpdateSubscriptionStatus :exec
UPDATE users SET subscription_status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateSubscriptionStatusParams struct {
	ID                 pgtype.UUID `json:"id"`
	SubscriptionStatus string      `json:"subscription_status"`
}

func (q *Queries) UpdateSubscriptionStatus(ctx context.Context, arg UpdateSubscriptionStatusParams) error {
	_, err := q.db.Exec(ctx, updateSubscriptionStatus, arg.ID, arg.SubscriptionStatus)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (discord_id, discord_username, email, avatar_url)
VALUES ($1, $2, $3, $4)
ON CONFLICT (discord_id) DO UPDATE SET
    discord_username = EXCLUDED.discord_username,
    email = EXCLUDED.email,
    avatar_url = EXCLUDED.avatar_url,
    updated_at = NOW()
RETURNING id, discord_id, discord_username, email, avatar_url, stripe_customer_id, subscription_status, trial_ends_at, created_at, updated_at
`

type UpsertUserParams struct {
	DiscordID       string      `json:"discord_id"`
	DiscordUsername string      `json:"discord_username"`
	Email           string      `json:"email"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.DiscordID,
		arg.DiscordUsername,
		arg.Email,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.DiscordID,
		&i.DiscordUsername,
		&i.Email,
		&i.AvatarUrl,
		&i.StripeCustomerID,
		&i.SubscriptionStatus,
		&i.TrialEndsAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
